### ISSUE TITLE
typo? 'dns' instead of 'dsn'

### ISSUE THREAD

**Issue by einSelbst** [natterstefan/next-with-sentry#4]
I was just wondering about this line and wanted to bring it to your attention in case of a typo. Feel free to close this issue. https://github.com/natterstefan/next-with-sentry/blob/3e52d41cb1f3835e30fa834c9e6015c58161b179/next.config.js#L16

**Comment by natterstefan** [comment]
Hi @einSelbst. 👋

😅  That's indeed a typo. Thanks for making me aware of that. I'll fix that tonight.
